### ISSUE TITLE
updateAttributesInterval should be removed from documentation

### ISSUE THREAD

**Issue by come-nc** [nextcloud/documentation#9500] opened 2022-12-22 08:55 UTC
Hello,

https://docs.nextcloud.com/server/latest/admin_manual/configuration_user/user_auth_ldap.html#attribute-update-interval

This section is outdated since https://github.com/nextcloud/server/pull/22583

The configuration key updateAttributesInterval is not used anymore.
I am not sure if the whole section should be removed, or only the last part with the command.
@blizzz Can you give a recommendation?

**Comment by joshtrichards** [comment] 2023-11-01 14:00
Duplicate of #11088

**Closed by joshtrichards** 2023-11-01 14:00 UTC
Labels: bug, needs info, manual: admin, feature: ldap
