### ISSUE TITLE
nginx 301 'well known' change needed to support http2

### ISSUE THREAD

**Issue by hcoin** [nextcloud/documentation#7137] opened 2021-09-20 21:53 UTC
The current nginx config for 'well known' addresses follows the pattern

        location = /.well-known/caldav  { return 301 /remote.php/dav/;  }

which is fine except when nginx is behind a proxy or using http2.  In those cases, the redirect adds the non-standard port/protocol (usually 8443 instead of 443) and the direct fails-- as that port is not exposed to the client.  I suggest changing all 301's along the lines

        location = /.well-known/caldav  { return 301 https://$server_name/remote.php/dav/; }
which will force the client to use the 443 port, and allow the proxy / load balancing logic to do its work properly.

**Comment by joshtrichards** [comment] 2024-02-26 02:00
Duplicate of #899

**Closed by joshtrichards** 2024-02-26 02:00 UTC
Labels: enhancement, manual: admin, feature: install and update
