### ISSUE TITLE
Non-English manuals should be translations of English master

### ISSUE THREAD

**Issue by vasyugan** [nextcloud/documentation#1832] opened 2020-02-20 10:26 UTC
This is maybe a broader issue, which is not easily fixed, but when contributing a little to the documentation on Thunderbird and its integration with Nextcloud calendar and contacts, I saw that the [English](https://github.com/nextcloud/documentation/blob/master/user_manual/pim/sync_thunderbird.rst) and the [German](https://github.com/nextcloud/documentation/blob/master/user_manual_de/pim/sync_thunderbird.rst) versions are substantially different.  (I did a bit of fixing there but my fixes are incomplete)

Shouldn't the non-English versions be exact translations of the English one? Isn't there a standard for internationalisation of FLOSS software, with .po files / gettext, meaning that the non-English manuals shouldn't be part of this tree at all but rather be handled by a seperate translation process? Else it is a bit like Wikipedia, where every language version does their own thing with little coordination between the language versions. To me this doesn't look feasible.

**Comment by valerio-bozzolan** [comment] 2020-03-19 09:24
I strongly suggest to the nextCloud team to migrate the documentation in a MediaWiki instance. With the extension Translate it will be super-easy to translate everything.

This is an example of some Translated pages:
https://www.mediawiki.org/wiki/Help:Navigation
https://www.mediawiki.org/wiki/Help:Navigation/es
https://www.mediawiki.org/wiki/Help:Navigation/it

This is the super-simple translation interface (in this case is even public for everyone, but you can change it):
https://www.mediawiki.org/w/index.php?title=Special:Translate&group=page-Help%3ANavigation&language=fr&action=page&filter=

**Comment by aol-nnov** [comment] 2020-04-01 05:59
Quite agree with @vasyugan!

There is a chapter in the readthedocs, ahem, docs explaining how to utilise gettext for translation: https://docs.readthedocs.io/en/stable/guides/manage-translations.html and later integrate with transifex.

BTW, [translation link](https://www.transifex.com/indiehosters/nextcloud-user-documentation/), mentioned in the [latest docs](https://docs.nextcloud.com/server/18/user_manual/) yields 404

**Comment by skjnldsv** [comment] 2020-04-01 10:11
Yeeep, that would be very awesome!
Unfortunately this requires a great amount of changes and we don't have the human nor time ressources right now! :(
If anyone want to dive on this, feel free, we'll be happy to assist you! :hugs:

**Comment by valerio-bozzolan** [comment] 2020-04-02 10:43
> Yeeep, that would be very awesome!
> Unfortunately this requires a great amount of changes and we don't have the human nor time ressources right now! :(
> If anyone want to dive on this, feel free, we'll be happy to assist you! hugs

That's a good starting point. We can provide some hardware and technical resources to create a MediaWiki instance for you. The documentation provided in this way could be released under CC BY-SA in order that you can dump it anytime.

In the other hand it's not clear to me if the official documentation is already under a free cultural work license, to start something from it and allowing the community to work, instead of doing a complete rewrite. Can you just clarify this point?

**Comment by aol-nnov** [comment] 2020-04-02 10:53
@valerio-bozzolan why are you so biased towards wiki engine? IMHO, readthedocs is quite decent platform and it's quite popular nowadays. It is a cloud solution provided free of charge, supporting integrations with collaborative translation platforms.

Also, it provides means to download offline docs, too.

With readthedocs documentation source code is hosted under git allowing merge requests for docs improvements.

Not sure if wiki angine will cover all those aspects...

**Comment by skjnldsv** [comment] 2020-04-02 13:10
> In the other hand it's not clear to me if the official documentation is already under a free cultural work license, to start something from it and allowing the community to going on, instead of doing a complete rewrite to avoid any legal issue. Can you just clarify this point?

cc @jospoortvliet

**Comment by valerio-bozzolan** [comment] 2020-04-03 07:03
> IMHO, readthedocs is quite decent platform and it's quite popular nowadays. It is a cloud solution provided free of charge, supporting integrations with collaborative translation platforms.

I'm interested in boosting the translation process, allowing non-tech translators volunteers in contributing, because actually I see this problem: very few people are contributing in this sector. So much years are passed since the first release, but our user documentation covers exactly 3 languages. That's a problem for the adoption of this software.

The good news is that something could be changed and without much efforts. For example just trying another platform loved by translators.

> Also, it provides means to download offline docs, too.

Yep that's important, but that's covered too:
https://www.mediawiki.org/w/index.php?title=Special:ElectronPdf&page=Help%3ANavigation/it
https://www.mediawiki.org/w/index.php?title=Special:ElectronPdf&page=Help%3ANavigation/en

> With readthedocs documentation source code is hosted under git allowing merge requests for docs improvements.

My friend, you found the problem: translators often does not know git, do not love it, or they have not the time for a merge request, because maybe they have time to just contribute on 2-3 paragraphs in their 5 minutes spare time in dinner pause.

This involves a kind of real-time collaboration that is inefficient with git, and that's why actually our documentation is covered in 3 languages, sadly without even stubs in other languages.

> Not sure if wiki angine will cover all those aspects...

Well, not to spam MediaWiki, but it has batteries included for this stuff :)

* [example of stats page](https://www.mediawiki.org/wiki/Special:MessageGroupStats?group=page-Help%3ANavigation&suppressempty=1&language=de&x=D)
* [example of translation page](https://www.mediawiki.org/w/index.php?title=Special:MessageGroupStats&language=de&group=page-Help%3ANavigation)

> why are you so biased towards wiki engine? 

Actually I have just some interest in involve more people in this process.

**Comment by vasyugan** [comment] 2020-04-03 08:36
There are ways of hiding the complexity of gettext-based translation. See https://hosted.weblate.org/ Many free software projects are using it already.

**Comment by aol-nnov** [comment] 2020-04-03 09:17
@vasyugan actually, I was meant to mention weblate (we're using it internally for gui localisation), but I did not find any references on how to integrate it with readthedocs.

To be frank, as of now, the whole pipeline of delivering git docs to the readthe docs is a bit vague for me. May be, there is no need to integrate weblate with readthedocs and readthedocs will itself pull latest git revision to render all the docs. I will need to dig documentetion a bit to make more clear statements...

**Comment by valerio-bozzolan** [comment] 2020-04-03 12:51
> There are ways of hiding the complexity of gettext-based translation. See https://hosted.weblate.org/ Many free software projects are using it already.
> [sorry, I overlooked the post about Transifex, which seems to plug in nicely to the existing system]

In addition of what @aol-nnov said, note that Weblate is very efficient for translating user interfaces, or other one-way contributions, where you want an upstream string to be translated in multiple languages. In the other hand, with Weblate or similar solutions you do not simplify the contribution and the expansion of the original English version as-well.

**Comment by jospoortvliet** [comment] 2020-04-03 14:55
So we've discussed this a bunch of times. We'd love to make our docs easier to both edit and translate. But there are some requirements:
* [ ] must be easy to get or generate a PDF out of it which we can ship - that generation should be able to be part of our scripted "build releases". So any hosted solution should have an API at least, or a PDF download or something...
* [ ] the docs are, I think GPL, or CC or something - that should ofc always be that way
* [ ] I probably forgot some hard requirements, will edit this while I think more about it

Now the very-good-to-have are:
* [ ] easy to contribute to for external people
* [ ] easy to contribute to for our existing developers
    * So yes, git is sub-optimal for external people but keep in mind that 90% of the docs is written by the developers as they just wrote the feature(s) and they are VERY familiar with git... Git fits in their workflow as well and we can connect with the various git features so whatever we pick has to be a LOT better in almost everything before I'd even be willing to consider moving away from git. Developers are already often not crazy about writing docs (yeah yeah, they **HATE IT**, I know), if we make it harder for THEM we will have less docs, guaranteed. And having less and outdated but translated docs - not sure if that is a step up.
* [ ] easy to translate (so, this it is currently not...)
* [ ] easy to find on google (our current docs aren't that good at it, ppl find outdated stuff all the time, we have to put time in this at some point)
* [ ] should be really easy to migrate from what we currently have to whatever it should be because if it is more than a few clicks and lines of code from one of our sysadmins, don't count on it happening this year - we're totally overloaded.
* [ ] Related to that point, it should ideally not be ANOTHER thing our sysadmins have to host - at least not if it is anything that is not plain html. So the best solution is something that generates HTML we can just update, like what we have now.
* [ ] could be hosted somewhere else, sure. But then we'd rather not have to spend money on it (sorry, we're really not that rich a company, besides, we'd rather spend it on Nextcloud development) and of course third party stuff - always more risks so that's really not ideal. But possible.
* [ ] markdown as language, really really please. Not other weird stuff please. WYSIWYG is nice to have, sure, but most docs - will be written by devs and WYSIWYG does NOT help there. Plus, risk of lossy conversion.
* [ ] I can't think of much more right now but let's discuss it a bit more

Honestly, my idea solution would be something that allows us to run a process on one of our servers that takes our docs as they are here and gets them into Transifex so our existing community there can translate it and then generates HTML and PDF which we can put on our server and into Nextcloud.

Because that hits almost all the good points above:

* [x] nearly no work
* [x] no migration
* [x] ppl can keep editing where it is
* [x] no extra hosting costs or 3rd party stuff
* [x] keep markdown
* [x] and so on.

Any other solution is going to be problematic. Anyone know a way how to do it that way? Only if that's really not possible/feasible should we consider setting up an entirely new thing, converting everything etc etc etc...

**Comment by vasyugan** [comment] 2020-04-04 09:33
> 
> Honestly, my idea solution would be something that allows us to run a process on one of our servers that takes our docs as they are here and gets them into Transifex so our existing community there can translate it and then generates HTML and PDF which we can put on our server and into Nextcloud.
 
 If transifex is an option, then by all means, go for it! As it stands, the German manual receives only a couple of edits per year, it must be heavily outdated, so it should make way for an actual translation... Since a large number of Nextcloud's users speak German, there would be some urgency in that. And of course, having Spanish, Russian, French etc manuals would be great, if volunteers show up to translate them.

**Comment by jospoortvliet** [comment] 2020-04-14 08:34
> If transifex is an option, then by all means, go for it!

Well, yes, it would be ideal. But I don't KNOW if it is, and IF it is, somebody has to do the work, or at least the research so the 'work' can be done following a few predefined steps. The sysadmin team is sadly just too overloaded right now and they don't have time for it, as I said, at least for the next 4-6 months. So help welcome or - this won't happen any time soon.

**Comment by pierreozoux** [comment] 2020-05-09 12:53
@vasyugan if you want to discuss how to help people non familiar to git to improve documentation, please open a new issue. I think, like @jospoortvliet, that we have to use git.
But then, how to help them, is indeed open.

The translation issue is already tackled in #216.

I will close as the title suggests it is a duplicate of #216.

**Closed by pierreozoux** 2020-05-09 12:53 UTC
Labels: 1. to develop, enhancement
