### ISSUE TITLE
Documentation; Requesting folder and file count 

### ISSUE THREAD

**Issue by timosturm** [nextcloud/documentation#8191] opened 2022-04-16 18:25 UTC
```
curl -u username:password 'https://cloud.example.com/remote.php/dav/files/username/folder' -X PROPFIND --data '<?xml version="1.0" encoding="UTF-8"?>
 <d:propfind xmlns:d="DAV:">
   <d:prop xmlns:oc="http://owncloud.org/ns">
        <nc:contained-folder-count />
        <nc:contained-file-count />
   </d:prop>
 </d:propfind>'
```
(see https://docs.nextcloud.com/server/latest/developer_manual/client_apis/WebDAV/basic.html#requesting-properties)
returns 
```
<?xml version="1.0" encoding="utf-8"?>
<d:error xmlns:d="DAV:" xmlns:s="http://sabredav.org/ns">
  <s:exception>Sabre\DAV\Exception\BadRequest</s:exception>
  <s:message>Namespace prefix nc on contained-folder-count is not defined
 on line 4, column 32</s:message>
</d:error>
```

Replacing `nc` with `oc` returns `<d:propstat><d:prop><oc:contained-folder-count/><oc:contained-file-count/></d:prop><d:status>HTTP/1.1 404 Not Found</d:status>` for all folders and files in `folder`.

Is this an error in the documentation? Does this require some special server configuration to work?

**Comment by joshtrichards** [comment] 2023-08-19 20:12
I think the issue is your request is missing the `nc` namespace URI in the `d:propfind`:

https://docs.nextcloud.com/server/latest/developer_manual/client_apis/WebDAV/basic.html#a-note-about-namespaces-uri

The current documentation for requesting properties does appear to include both:

https://docs.nextcloud.com/server/latest/developer_manual/client_apis/WebDAV/basic.html#requesting-properties

Closing this is it, but feel free to follow-up/reopen if the currently documented method does not work for you.

**Closed** 2023-08-19 20:13 UTC
