### ISSUE TITLE
Question: Nextcloud IOS Documentation

### ISSUE THREAD

**Issue by FritzHerbers** [nextcloud/documentation#8143] opened 2022-03-20 15:43 UTC
Hi
Is there a documentation of the Nextcloud IOS App ?

- explaining usage
- technical insight how features are implemented (e.g. directory/filename concepts, when syncing starts, is syncing chunked, etc.), behavior.

Tried to look into the Android documentation, which gives a 404: https://docs.nextcloud.com/android/

Thanks in advance

**Comment by tflidd** [comment] 2022-04-17 21:58
If you cross-post, it's good to keep a link: https://github.com/nextcloud/ios/issues/1930

**Comment by tflidd** [comment] 2022-04-17 21:59
There was an issue for that: https://github.com/nextcloud/ios/issues/26 but it was closed....

**Comment by joshtrichards** [comment] 2023-09-18 18:23
Closing as a duplicate of nextcloud/ios#1930 for now since that already exists and also because historically the clients have maintained their own documentation (the desktop repository has its docs) or taken the approach of "Implement so that minimal to no documentation is necessary." The Android docs were abandoned and removed in #1583.

I do think it might be valuable to have a broader discussion about whether it's worthwhile either centralizing the desktop docs and/or expanding the existing User Manual to incorporate more coverage of the various clients. That, however, should get its own issue.

**Comment by joshtrichards** [comment] 2023-09-18 18:32
Created #11126 to track a broader discussion.

**Closed** 2023-09-18 18:32 UTC
Labels: enhancement, help wanted, manual: user, client: 🤖🍏 mobile
