### ISSUE TITLE
Add info to MacOS/iOS integration page that CALDAV stops working for MacOS 11.0 Big Sur

### ISSUE THREAD

**Issue by uiskla** [nextcloud/documentation#5916] opened 2021-01-10 19:03 UTC
Hi,

I just found after some hours of trial and error that the reminders.app in MacOS 11.0 Big Sur does not work with CALDAV servers anymore. When migrating from MacOS 10.15 the Reminders configuration for Nextcloud ist still present in the Reminders.app, but changes are not synchronized to the Nextcloud server. When deleting and re-adding the CALDAV connection to the Nextcloud server, only the calendar synchronization works. The Reminders.app does not show the task list from the Nextcloud. This issue is also extensively documented here:

https://help.nextcloud.com/t/reminders-app-does-not-display-nc-tasks/98359

Please add info the current Nextcloud documentation that this is an issue for the MacOS 11.0 Big Sur platform at this time and point them to alternative solutions, eg. Thunderbird+Lightning plugin. Note also that iOS 14 is not affected.

Kind regards

Peter

**Comment by BernieO** [comment] 2021-04-23 13:10
This problem is caused by 3rd party software manipulating the network stack (littlesnitch, etc.), which has been fixed with MacOS 11.2:
https://help.nextcloud.com/t/reminders-app-does-not-display-nc-tasks/98359/14

Without those 3rd party-software the reminder sync to/from MacOS 11 always worked.

**Closed by BernieO** 2021-04-23 13:10 UTC
