### ISSUE TITLE
Manage connected browsers and devices not compliant with actual UI

### ISSUE THREAD

**Issue by dhebert91** [nextcloud/documentation#1210] opened 2019-01-30 22:33 UTC
This file form the user manual is not updated. 
The screenshot are to old and the contents is not compliant with the actual user interface.

**Comment by joshtrichards** [comment] 2023-10-17 14:23
Duplicate of #1746 

Let's consolidate tracking progress/changes there. Thanks, @dhebert91!

**Closed by joshtrichards** 2023-10-17 14:23 UTC
Labels: manual: user, technical debt, feature: authentication
