### ISSUE TITLE
No chance to translate

### ISSUE THREAD

**Issue by bjarkan** [nextcloud/documentation#730] opened 2018-03-25 14:49 UTC
We live in a over-connected world, but sadly not everybody speak english. 

Why not having a chance to colaborate porting to another language de docs. Not only the apps and the interface are candidates for this.

Thanks

**Comment by tflidd** [comment] 2018-03-27 12:09
Duplicate of https://github.com/nextcloud/documentation/issues/216

I mean to remember that it was not easy to put in place with the current system. I can't find the reference for that, perhaps it was on help.nextcloud.com.

**Closed** 2018-03-27 12:12 UTC
